{
  "hash": "d1e102305208b117f7f2e9387318bb01",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"S0-01 notebook — R\"\nsubtitle: \"Compartments and ODEs from first principles\"\nexecute:\n  freeze: auto\n---\n\n\n\n\nEverything in the lesson, built from scratch and checked. Run it top to bottom.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(deSolve)\nlibrary(dplyr)\nlibrary(ggplot2)\ntheme_set(theme_minimal(base_size = 11))\n```\n:::\n\n\n\n\n## 1. One compartment, IV bolus — and a check you should always run\n\nWork in **amounts** inside the ODE and convert to concentration at the end.\nDoses in µg with volumes in L means µg/L, which reads directly as ng/mL.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCL <- 12; V <- 60          # L/h, L\nD  <- 50 * 1000            # 50 mg as ug\nk  <- CL / V\n\nt <- seq(0, 48, by = 0.1)\nsol <- ode(c(A = D), t, function(t, y, p) list(-k * y[\"A\"]),\n           parms = NULL, method = \"lsoda\", rtol = 1e-10, atol = 1e-12)\n\nnumeric  <- sol[, \"A\"] / V\nanalytic <- (D / V) * exp(-k * t)\n\ncat(sprintf(\"max relative error vs analytic : %.2e\\n\",\n            max(abs(numeric - analytic) / analytic)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmax relative error vs analytic : 9.75e-11\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"half-life                      : %.2f h\\n\", log(2) / k))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nhalf-life                      : 3.47 h\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"AUC(0-inf) numeric             : %.1f ng*h/mL\\n\",\n            sum(diff(t) * (head(numeric, -1) + tail(numeric, -1)) / 2) +\n              tail(numeric, 1) / k))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAUC(0-inf) numeric             : 4166.8 ng*h/mL\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"D / CL                         : %.1f ng*h/mL\\n\", D / CL))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nD / CL                         : 4166.7 ng*h/mL\n```\n\n\n:::\n:::\n\n\n\n\nTwo habits worth forming now. **Always validate numerics against an analytical\nsolution when one exists.** And **`AUC(0-inf) = D/CL` is exact for any linear\nmodel**, so it is a free correctness check on every simulation you ever write.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(t = t, conc = numeric) |>\n  ggplot(aes(t, conc)) + geom_line(linewidth = 0.7) +\n  scale_y_log10() + labs(x = \"Time (h)\", y = \"Conc (ng/mL)\",\n                         title = \"Semi-log — a straight line\")\n```\n\n::: {.cell-output-display}\n![](notebook-r_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n\n\n## 2. Add absorption\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\none_cmt_oral <- function(t, y, p) with(as.list(c(y, p)), {\n  list(c(A_gut = -ka * A_gut,\n         A_c   =  ka * A_gut - (CL / V) * A_c))\n})\n\nka <- 1.2\ntt <- seq(0, 48, by = 0.01)\ns  <- ode(c(A_gut = D, A_c = 0), tt, one_cmt_oral,\n          parms = c(ka = ka, CL = CL, V = V),\n          method = \"lsoda\", rtol = 1e-10, atol = 1e-12)\ncc <- s[, \"A_c\"] / V\n\ncat(sprintf(\"tmax numeric %.3f h   analytic %.3f h   Cmax %.1f ng/mL\\n\",\n            tt[which.max(cc)], log(ka / k) / (ka - k), max(cc)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntmax numeric 1.790 h   analytic 1.792 h   Cmax 582.4 ng/mL\n```\n\n\n:::\n:::\n\n\n\n\n### Flip-flop: when the terminal slope is absorption\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfor (ka_i in c(1.2, 0.05)) {\n  tg <- seq(0, 120, by = 0.1)\n  si <- ode(c(A_gut = D, A_c = 0), tg, one_cmt_oral,\n            parms = c(ka = ka_i, CL = CL, V = V),\n            method = \"lsoda\", rtol = 1e-10, atol = 1e-12)\n  ci <- si[, \"A_c\"] / V\n  m  <- tg > 72 & ci > 0\n  slope <- coef(lm(log(ci[m]) ~ tg[m]))[2]\n  cat(sprintf(\"ka = %5.2f /h  ->  terminal t1/2 from slope = %5.2f h\\n\",\n              ka_i, log(2) / -slope))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nka =  1.20 /h  ->  terminal t1/2 from slope =  3.47 h\nka =  0.05 /h  ->  terminal t1/2 from slope = 13.86 h\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"\\nelimination t1/2 = %.2f h    absorption t1/2 (ka = 0.05) = %.2f h\\n\",\n            log(2) / k, log(2) / 0.05))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nelimination t1/2 = 3.47 h    absorption t1/2 (ka = 0.05) = 13.86 h\n```\n\n\n:::\n:::\n\n\n\n\nThe slow-absorption curve's terminal slope reports the **absorption** half-life,\nnot the elimination half-life. Nothing in the fit tells you which one you are\nlooking at. Only an IV arm does.\n\n## 3. Two compartments — the CASE-SM structure\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhybrid <- function(CL, Vc, Q, Vp) {\n  k10 <- CL / Vc; k12 <- Q / Vc; k21 <- Q / Vp\n  s <- k10 + k12 + k21\n  d <- sqrt(s^2 - 4 * k10 * k21)\n  c(alpha = (s + d) / 2, beta = (s - d) / 2, k21 = k21)\n}\n\nconc_sd <- function(t, dose_mg, ka, CL, Vc, Q, Vp) {\n  h <- hybrid(CL, Vc, Q, Vp); a <- h[\"alpha\"]; b <- h[\"beta\"]; k21 <- h[\"k21\"]\n  A <- dose_mg * 1000 * ka / Vc\n  as.numeric(A * (((k21 - a) / ((ka - a) * (b - a))) * exp(-a * t) +\n                  ((k21 - b) / ((ka - b) * (a - b))) * exp(-b * t) +\n                  ((k21 - ka) / ((a - ka) * (b - ka))) * exp(-ka * t)))\n}\n\nTRUE_P <- list(ka = 1.2, CL = 12, Vc = 60, Q = 8, Vp = 90)   # CASE-SM typical values\n\node_sd <- function(t, dose_mg, ka, CL, Vc, Q, Vp) {\n  rhs <- function(t, y, p) with(as.list(y), list(c(\n    A_gut = -ka * A_gut,\n    A_c   =  ka * A_gut - (CL / Vc) * A_c - (Q / Vc) * A_c + (Q / Vp) * A_p,\n    A_p   =  (Q / Vc) * A_c - (Q / Vp) * A_p)))\n  s <- ode(c(A_gut = dose_mg * 1000, A_c = 0, A_p = 0), c(0, t), rhs,\n           parms = NULL, method = \"lsoda\", rtol = 1e-11, atol = 1e-13)\n  (s[-1, \"A_c\"]) / Vc\n}\n\ntg <- seq(0.01, 72, length.out = 200)\nan <- do.call(conc_sd, c(list(t = tg, dose_mg = 50), TRUE_P))\nnu <- do.call(ode_sd,  c(list(t = tg, dose_mg = 50), TRUE_P))\nh  <- hybrid(TRUE_P$CL, TRUE_P$Vc, TRUE_P$Q, TRUE_P$Vp)\n\ncat(sprintf(\"analytic vs ODE, max relative error : %.1e\\n\", max(abs(an - nu) / nu)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nanalytic vs ODE, max relative error : 1.2e-10\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"distribution t1/2 (alpha)           : %.2f h\\n\", log(2) / h[\"alpha\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndistribution t1/2 (alpha)           : 1.85 h\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"terminal     t1/2 (beta)            : %.2f h\\n\", log(2) / h[\"beta\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nterminal     t1/2 (beta)            : 14.61 h\n```\n\n\n:::\n:::\n\n\n\n\nTwo half-lives, differing eight-fold. Quoting \"the\" half-life of this compound\nwithout saying which one is meaningless.\n\n## 4. Multiple dosing by superposition\n\nFor a **linear** model the response to repeated doses is the sum of the\nresponses to each dose alone — not an approximation. It gives you a fast\nsimulator and an exact check at once.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconc_md <- function(t, dose_mg, ka, CL, Vc, Q, Vp, n_doses = 21, tau = 24) {\n  out <- numeric(length(t))\n  for (i in seq_len(n_doses) - 1) {\n    dt <- t - i * tau\n    ok <- dt >= 0\n    if (any(ok)) out[ok] <- out[ok] + conc_sd(dt[ok], dose_mg, ka, CL, Vc, Q, Vp)\n  }\n  out\n}\n\ntrapz <- function(x, y) sum(diff(x) * (head(y, -1) + tail(y, -1)) / 2)\n\ng1  <- seq(0, 24, length.out = 24001)\ngss <- seq(480, 504, length.out = 24001)\nauc1  <- trapz(g1,  do.call(conc_md, c(list(t = g1,  dose_mg = 50), TRUE_P)))\ncss   <- do.call(conc_md, c(list(t = gss, dose_mg = 50), TRUE_P))\naucss <- trapz(gss, css)\n\ncat(sprintf(\"AUC(0-24) day 1        : %8.1f ng*h/mL\\n\", auc1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAUC(0-24) day 1        :   3424.3 ng*h/mL\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"AUC(tau) steady state  : %8.1f ng*h/mL\\n\", aucss))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAUC(tau) steady state  :   4166.7 ng*h/mL\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Dose / CL              : %8.1f ng*h/mL   <- must match exactly\\n\", 50000 / TRUE_P$CL))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDose / CL              :   4166.7 ng*h/mL   <- must match exactly\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"accumulation ratio     : %8.3f\\n\", aucss / auc1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\naccumulation ratio     :    1.217\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"steady-state Cmax %.1f, Cmin %.1f ng/mL\\n\", max(css), min(css)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsteady-state Cmax 560.7, Cmin 51.9 ng/mL\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntf <- seq(0, 504, by = 0.1)\ntibble(day = tf / 24, conc = do.call(conc_md, c(list(t = tf, dose_mg = 50), TRUE_P))) |>\n  filter(conc > 0) |>\n  ggplot(aes(day, conc)) + geom_line(linewidth = 0.5) + scale_y_log10() +\n  labs(x = \"Day\", y = \"Conc (ng/mL)\",\n       title = \"CASE-SM, 50 mg once daily — approach to steady state\")\n```\n\n::: {.cell-output-display}\n![](notebook-r_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n\nNote how quickly the troughs plateau despite a 14.6 h terminal half-life: the\naccumulation ratio is 1.22, not the ~3 that a single-exponential intuition\nwould predict.\n\n## 5. Failure mode — a converged, meaningless fit\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf    <- read.csv(\"../../cases/case-sm/data/ozanib_pk.csv\")\ntruth <- read.csv(\"../../cases/case-sm/data/ozanib_individual_truth.csv\")\n\nobs <- df |> filter(EVID == 0, !is.na(DV), DAY == 1, TIME > 0)\nsid <- obs |> count(ID) |> slice_max(n, n = 1) |> pull(ID) |> first()\nsub <- obs |> filter(ID == sid)\ndose <- sub$DOSE[1]\ntr   <- truth |> filter(ID == sid)\nsparse <- sub |> filter(TIME %in% c(0.5, 4, 12))\n\nobj <- function(logp, tt, yy) {\n  p <- exp(pmin(pmax(logp, -6), 8))\n  pred <- pmax(conc_sd(tt, dose, p[1], p[2], p[3], p[4], p[5]), 1e-8)\n  sum((log(pred) - log(yy))^2)\n}\n\np0 <- log(c(1, 10, 50, 6, 80))\ncat(sprintf(\"subject %d at %g mg\\n\", sid, dose))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsubject 1 at 25 mg\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"%-18s ka %5.2f  CL %6.2f  Vc %6.1f  Q %6.2f  Vp %7.1f\\n\",\n            \"TRUTH\", tr$KA, tr$CL, tr$VC, tr$Q, tr$VP))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTRUTH              ka  1.27  CL  19.25  Vc   88.6  Q  11.84  Vp   151.7\n```\n\n\n:::\n\n```{.r .cell-code}\nfor (nm in c(\"rich\", \"sparse\")) {\n  d <- if (nm == \"rich\") sub else sparse\n  fit <- optim(p0, obj, tt = d$TIME, yy = d$DV,\n               method = \"BFGS\", control = list(maxit = 5000, reltol = 1e-12))\n  e <- exp(fit$par)\n  cat(sprintf(\"%-18s ka %5.2f  CL %6.2f  Vc %6.1f  Q %6.2f  Vp %7.1f  | rmse(log) %.3f\\n\",\n              sprintf(\"%s, %d points\", nm, nrow(d)),\n              e[1], e[2], e[3], e[4], e[5], sqrt(fit$value / nrow(d))))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrich, 8 points     ka  1.03  CL  28.69  Vc   72.8  Q  24.64  Vp    51.0  | rmse(log) 0.117\nsparse, 3 points   ka  1.35  CL  31.59  Vc  107.7  Q  18.24  Vp    88.3  | rmse(log) 0.000\n```\n\n\n:::\n:::\n\n\n\n\nThe three-point fit reaches a residual error of essentially **zero**: five\nparameters passing through three points can always be made to fit perfectly,\nand the optimiser reports success. The rich fit is honest but still recovers\n`Q` and `Vp` poorly from eight oral samples in one individual — which is not a\nbug in your code, but the reason population modeling (`S2`) exists.\n\n::: {.callout-important}\nConvergence is not evidence. A perfect fit is a warning sign rather than a\ntriumph. Look at parameter correlations and conditioning before you look at the\nestimates.\n:::\n\n## 6. A trap that is really in the data\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredose <- df |> filter(EVID == 0, DAY == 1, TIME == 0)\ncat(sprintf(\"pre-dose samples: %d   flagged BLQ: %d   reported as a real number: %d\\n\",\n            nrow(predose), sum(predose$BLQ), sum(!is.na(predose$DV))))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npre-dose samples: 60   flagged BLQ: 58   reported as a real number: 2\n```\n\n\n:::\n\n```{.r .cell-code}\npredose |> filter(!is.na(DV)) |> select(ID, TIME, DV, IPRED_TRUE, BLQ) |> head(8)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| ID| TIME|     DV| IPRED_TRUE| BLQ|\n|--:|----:|------:|----------:|---:|\n| 29|    0| 1.4749|          0|   0|\n| 43|    0| 1.1808|          0|   0|\n\n</div>\n:::\n:::\n\n\n\n\nThe true concentration before the first dose is exactly zero, but the assay has\nadditive error, so some pre-dose samples come back as small positive numbers.\nFeed one into a log-scale objective and it contributes a residual of about 18\nand drags the whole fit with it. That is why section 5 filters `TIME > 0`.\n`S0-03` is about catching this class of problem before it reaches the model.\n\n## What to try next\n\n1. Refit the rich profile with `Q` and `Vp` fixed at the truth. How much better\n   are `CL` and `Vc`? That is the value of borrowing strength, measured.\n2. Simulate a missed dose on day 10 (drop one term from the superposition sum)\n   and see how long the trough takes to recover.\n3. Set `ka = 0.15` and refit. Can you tell from the fit alone that you are in\n   flip-flop?\n",
    "supporting": [
      "notebook-r_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}