{
  "hash": "0064de59bc94822913bd59efb8fbff87",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"S0-01 notebook — Python\"\nsubtitle: \"Compartments and ODEs from first principles\"\njupyter: python3\nexecute:\n  freeze: auto\n---\n\n\n\n\nEverything in the lesson, built from scratch and checked. Run it top to bottom.\n\n::: {#d163aa83 .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nfrom scipy.integrate import solve_ivp\nfrom scipy.optimize import least_squares\n\nplt.rcParams.update({\"figure.figsize\": (7, 4.2), \"axes.grid\": True,\n                     \"grid.alpha\": 0.25, \"font.size\": 10})\n\n# NumPy 2.0 renamed trapz -> trapezoid. Bind once so this notebook runs on either.\ntrapz = np.trapezoid if hasattr(np, \"trapezoid\") else np.trapz\n```\n:::\n\n\n## 1. One compartment, IV bolus — and a check you should always run\n\nWork in **amounts** inside the ODE and convert to concentration at the end.\nDoses in µg with volumes in L means µg/L, which reads directly as ng/mL.\n\n::: {#319bc085 .cell execution_count=2}\n``` {.python .cell-code}\nCL, V = 12.0, 60.0          # L/h, L\nD = 50 * 1000.0             # 50 mg as ug\nk = CL / V\n\nt = np.linspace(0, 48, 481)\nsol = solve_ivp(lambda t, y: [-k * y[0]], (0, 48), [D], t_eval=t,\n                method=\"LSODA\", rtol=1e-10, atol=1e-12)\nnumeric = sol.y[0] / V\nanalytic = (D / V) * np.exp(-k * t)\n\nprint(f\"max relative error vs analytic : {np.max(np.abs(numeric - analytic) / analytic):.2e}\")\nprint(f\"half-life                      : {np.log(2) / k:.2f} h\")\nprint(f\"AUC(0-inf) numeric             : {trapz(numeric, t) + numeric[-1] / k:.1f} ng*h/mL\")\nprint(f\"D / CL                         : {D / CL:.1f} ng*h/mL\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmax relative error vs analytic : 1.38e-09\nhalf-life                      : 3.47 h\nAUC(0-inf) numeric             : 4166.8 ng*h/mL\nD / CL                         : 4166.7 ng*h/mL\n```\n:::\n:::\n\n\nTwo habits worth forming now. **Always validate numerics against an analytical\nsolution when one exists** — an error of 1e-10 means the solver settings are\nfine; an error of 1e-3 means they are not. And **`AUC(0-inf) = D/CL` is exact\nfor any linear model**, so it is a free correctness check on every simulation\nyou ever write.\n\n::: {#6173ee6a .cell execution_count=3}\n``` {.python .cell-code}\nfig, ax = plt.subplots(1, 2)\nax[0].plot(t, numeric); ax[0].set(xlabel=\"Time (h)\", ylabel=\"Conc (ng/mL)\", title=\"linear\")\nax[1].semilogy(t, numeric); ax[1].set(xlabel=\"Time (h)\", title=\"semi-log — a straight line\")\nplt.tight_layout()\n```\n\n::: {.cell-output .cell-output-display}\n![](notebook-py_files/figure-html/cell-4-output-1.png){width=669 height=394}\n:::\n:::\n\n\n## 2. Add absorption\n\n::: {#6cd3b230 .cell execution_count=4}\n``` {.python .cell-code}\ndef one_cmt_oral(t, y, ka, CL, V):\n    a_gut, a_c = y\n    return [-ka * a_gut, ka * a_gut - (CL / V) * a_c]\n\nka = 1.2\ntt = np.linspace(0, 48, 4801)\ns = solve_ivp(one_cmt_oral, (0, 48), [D, 0.0], t_eval=tt, args=(ka, CL, V),\n              method=\"LSODA\", rtol=1e-10, atol=1e-12)\nc = s.y[1] / V\n\ntmax_numeric = tt[c.argmax()]\ntmax_analytic = np.log(ka / k) / (ka - k)\nprint(f\"tmax numeric {tmax_numeric:.3f} h   analytic {tmax_analytic:.3f} h   Cmax {c.max():.1f} ng/mL\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntmax numeric 1.790 h   analytic 1.792 h   Cmax 582.4 ng/mL\n```\n:::\n:::\n\n\n### Flip-flop: when the terminal slope is absorption\n\n::: {#5792079d .cell execution_count=5}\n``` {.python .cell-code}\nfig, ax = plt.subplots()\nfor ka_i, label in [(1.2, \"ka = 1.2 /h  (absorption fast)\"),\n                    (0.05, \"ka = 0.05 /h (absorption slow)\")]:\n    tg = np.linspace(0, 120, 1201)\n    si = solve_ivp(one_cmt_oral, (0, 120), [D, 0.0], t_eval=tg, args=(ka_i, CL, V),\n                   method=\"LSODA\", rtol=1e-10, atol=1e-12)\n    ci = si.y[1] / V\n    m = (tg > 72) & (ci > 0)\n    slope = np.polyfit(tg[m], np.log(ci[m]), 1)[0]\n    print(f\"{label:35s} terminal t1/2 from slope = {np.log(2) / -slope:5.2f} h\")\n    ax.semilogy(tg, ci, label=label)\nax.set(xlabel=\"Time (h)\", ylabel=\"Conc (ng/mL)\"); ax.legend(); plt.tight_layout()\n\nprint(f\"\\nelimination t1/2 = {np.log(2) / k:.2f} h    absorption t1/2 (ka=0.05) = {np.log(2) / 0.05:.2f} h\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nka = 1.2 /h  (absorption fast)      terminal t1/2 from slope =  3.47 h\nka = 0.05 /h (absorption slow)      terminal t1/2 from slope = 13.86 h\n\nelimination t1/2 = 3.47 h    absorption t1/2 (ka=0.05) = 13.86 h\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](notebook-py_files/figure-html/cell-6-output-2.png){width=661 height=394}\n:::\n:::\n\n\nThe slow-absorption curve's terminal slope reports **13.9 h**, which is the\nabsorption half-life, not the 3.5 h elimination half-life. Nothing in the fit\ntells you which one you are looking at. Only an IV arm does.\n\n## 3. Two compartments — the CASE-SM structure\n\n::: {#806126c7 .cell execution_count=6}\n``` {.python .cell-code}\ndef hybrid(CL, Vc, Q, Vp):\n    \"\"\"Return (alpha, beta, k21) — the hybrid rate constants.\"\"\"\n    k10, k12, k21 = CL / Vc, Q / Vc, Q / Vp\n    s = k10 + k12 + k21\n    d = np.sqrt(s * s - 4 * k10 * k21)\n    return (s + d) / 2, (s - d) / 2, k21\n\n\ndef conc_sd(t, dose_mg, ka, CL, Vc, Q, Vp):\n    \"\"\"Analytic two-compartment oral single dose, ng/mL.\"\"\"\n    t = np.asarray(t, float)\n    a, b, k21 = hybrid(CL, Vc, Q, Vp)\n    A = dose_mg * 1000.0 * ka / Vc\n    term = (((k21 - a) / ((ka - a) * (b - a))) * np.exp(-a * t)\n            + ((k21 - b) / ((ka - b) * (a - b))) * np.exp(-b * t)\n            + ((k21 - ka) / ((a - ka) * (b - ka))) * np.exp(-ka * t))\n    return np.where(t >= 0, A * term, 0.0)\n\n\nTRUE = dict(ka=1.2, CL=12.0, Vc=60.0, Q=8.0, Vp=90.0)   # CASE-SM typical values\n\ndef ode_sd(t, dose_mg, ka, CL, Vc, Q, Vp):\n    def rhs(tt, y):\n        ag, ac, ap = y\n        return [-ka * ag,\n                ka * ag - (CL / Vc) * ac - (Q / Vc) * ac + (Q / Vp) * ap,\n                (Q / Vc) * ac - (Q / Vp) * ap]\n    s = solve_ivp(rhs, (0, max(t)), [dose_mg * 1000.0, 0, 0], t_eval=t,\n                  method=\"LSODA\", rtol=1e-11, atol=1e-13)\n    return s.y[1] / Vc\n\ntg = np.linspace(0.01, 72, 200)\nerr = np.max(np.abs(conc_sd(tg, 50, **TRUE) - ode_sd(tg, 50, **TRUE)) / ode_sd(tg, 50, **TRUE))\na, b, _ = hybrid(TRUE[\"CL\"], TRUE[\"Vc\"], TRUE[\"Q\"], TRUE[\"Vp\"])\nprint(f\"analytic vs ODE, max relative error : {err:.1e}\")\nprint(f\"distribution t1/2 (alpha)           : {np.log(2) / a:.2f} h\")\nprint(f\"terminal     t1/2 (beta)            : {np.log(2) / b:.2f} h\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nanalytic vs ODE, max relative error : 2.3e-11\ndistribution t1/2 (alpha)           : 1.85 h\nterminal     t1/2 (beta)            : 14.61 h\n```\n:::\n:::\n\n\nTwo half-lives, differing eight-fold. Quoting \"the\" half-life of this compound\nwithout saying which one is meaningless.\n\n## 4. Multiple dosing by superposition\n\nFor a **linear** model, the response to repeated doses is the sum of the\nresponses to each dose alone. That is not an approximation — and it gives you a\nfast simulator and an exact check at once.\n\n::: {#234d5877 .cell execution_count=7}\n``` {.python .cell-code}\ndef conc_md(t, dose_mg, ka, CL, Vc, Q, Vp, n_doses=21, tau=24.0):\n    t = np.asarray(t, float)\n    out = np.zeros_like(t)\n    for i in range(n_doses):\n        dt = t - i * tau\n        out += np.where(dt >= 0, conc_sd(np.maximum(dt, 0), dose_mg, ka, CL, Vc, Q, Vp), 0.0)\n    return out\n\ng_day1 = np.linspace(0, 24, 24001)\ng_ss = np.linspace(480, 504, 24001)\nauc_1 = trapz(conc_md(g_day1, 50, **TRUE), g_day1)\nauc_ss = trapz(conc_md(g_ss, 50, **TRUE), g_ss)\ncss = conc_md(g_ss, 50, **TRUE)\n\nprint(f\"AUC(0-24) day 1        : {auc_1:8.1f} ng*h/mL\")\nprint(f\"AUC(tau) steady state  : {auc_ss:8.1f} ng*h/mL\")\nprint(f\"Dose / CL              : {50000 / TRUE['CL']:8.1f} ng*h/mL   <- must match exactly\")\nprint(f\"accumulation ratio     : {auc_ss / auc_1:8.3f}\")\nprint(f\"steady-state Cmax {css.max():.1f}, Cmin {css.min():.1f} ng/mL\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAUC(0-24) day 1        :   3424.3 ng*h/mL\nAUC(tau) steady state  :   4166.7 ng*h/mL\nDose / CL              :   4166.7 ng*h/mL   <- must match exactly\naccumulation ratio     :    1.217\nsteady-state Cmax 560.7, Cmin 51.9 ng/mL\n```\n:::\n:::\n\n\n::: {#05b8ece3 .cell execution_count=8}\n``` {.python .cell-code}\ntfull = np.linspace(0, 504, 5041)\nplt.semilogy(tfull / 24, conc_md(tfull, 50, **TRUE))\nplt.xlabel(\"Day\"); plt.ylabel(\"Conc (ng/mL)\")\nplt.title(\"CASE-SM, 50 mg once daily — approach to steady state\")\nplt.tight_layout()\n```\n\n::: {.cell-output .cell-output-display}\n![](notebook-py_files/figure-html/cell-9-output-1.png){width=661 height=394}\n:::\n:::\n\n\nNote how quickly the troughs plateau despite a 14.6 h terminal half-life: the\naccumulation ratio is 1.22, not the ~3 that a single-exponential intuition would\npredict.\n\n## 5. Failure mode — a converged, meaningless fit\n\nFit the five-parameter model to one subject's rich day-1 profile, then to three\npoints from the same profile. Watch what the residuals do.\n\n::: {#8e054b8a .cell execution_count=9}\n``` {.python .cell-code}\ndf = pd.read_csv(\"../../cases/case-sm/data/ozanib_pk.csv\")\ntruth = pd.read_csv(\"../../cases/case-sm/data/ozanib_individual_truth.csv\")\n\nobs = df[(df.EVID == 0) & (df.DV.notna()) & (df.DAY == 1) & (df.TIME > 0)]\nsid = int(obs.groupby(\"ID\").size().idxmax())\nsub = obs[obs.ID == sid]\ndose = float(sub.DOSE.iloc[0])\ntr = truth[truth.ID == sid].iloc[0]\nsparse = sub[sub.TIME.isin([0.5, 4.0, 12.0])]\n\ndef resid(logp, tt, yy):\n    ka, CL, Vc, Q, Vp = np.exp(np.clip(logp, -6, 8))\n    return np.log(np.maximum(conc_sd(tt, dose, ka, CL, Vc, Q, Vp), 1e-8)) - np.log(yy)\n\np0 = np.log([1.0, 10.0, 50.0, 6.0, 80.0])\nprint(f\"subject {sid} at {dose:g} mg\")\nprint(f\"{'TRUTH':<18} ka {tr.KA:5.2f}  CL {tr.CL:6.2f}  Vc {tr.VC:6.1f}  Q {tr.Q:6.2f}  Vp {tr.VP:7.1f}\")\n\nfor label, d in [(f\"rich, {len(sub)} points\", sub), (\"sparse, 3 points\", sparse)]:\n    r = least_squares(resid, p0, args=(d.TIME.values, d.DV.values),\n                      method=\"trf\", max_nfev=8000)\n    e = np.exp(r.x)\n    cond = np.linalg.cond(r.jac.T @ r.jac)\n    print(f\"{label:<18} ka {e[0]:5.2f}  CL {e[1]:6.2f}  Vc {e[2]:6.1f}  Q {e[3]:6.2f}  Vp {e[4]:7.1f}\"\n          f\"  | rmse(log) {np.sqrt(np.mean(r.fun**2)):.3f}  cond {cond:.0e}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nsubject 1 at 25 mg\nTRUTH              ka  1.27  CL  19.25  Vc   88.6  Q  11.84  Vp   151.7\nrich, 8 points     ka  1.03  CL  28.69  Vc   72.8  Q  24.64  Vp    51.0  | rmse(log) 0.117  cond 4e+09\nsparse, 3 points   ka  1.59  CL  31.78  Vc  122.5  Q  15.62  Vp    79.6  | rmse(log) 0.000  cond 2e+18\n```\n:::\n:::\n\n\nThe three-point fit has a residual error of **exactly zero** and a condition\nnumber around 1e18 — numerically singular. Five parameters passing through three\npoints can always be made to fit perfectly, and the optimiser reports success.\n\nThe rich fit is honest but still imperfect: `Q` and `Vp` are recovered poorly\nfrom eight oral samples in one individual. That is not a bug in your code — it\nis why population modeling (`S2`) exists. Borrowing strength across subjects is\nwhat makes those parameters estimable at all.\n\n::: {.callout-important}\nThree things this section should leave you with: convergence is not evidence,\na perfect fit is a warning sign rather than a triumph, and you should look at\nthe condition number of $J^\\top J$ before you look at the parameter estimates.\n:::\n\n## 6. A trap that is really in the data\n\n::: {#2eacdb66 .cell execution_count=10}\n``` {.python .cell-code}\npredose = df[(df.EVID == 0) & (df.DAY == 1) & (df.TIME == 0)]\nsurvivors = predose[predose.DV.notna()]          # assay noise pushed these above the LLOQ\nprint(f\"pre-dose samples: {len(predose)}   flagged BLQ: {int(predose.BLQ.sum())}   \"\n      f\"reported as a real number: {len(survivors)}\")\nprint(survivors[[\"ID\", \"TIME\", \"DV\", \"IPRED_TRUE\", \"BLQ\"]].head(8).to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\npre-dose samples: 60   flagged BLQ: 58   reported as a real number: 2\n ID  TIME     DV  IPRED_TRUE  BLQ\n 29   0.0 1.4749         0.0    0\n 43   0.0 1.1808         0.0    0\n```\n:::\n:::\n\n\nThe true concentration before the first dose is exactly zero, but the assay has\nadditive error, so some pre-dose samples come back as small positive numbers.\nFeed one of those into a log-scale objective and it will contribute a residual of\n`log(1.5) - log(1e-8)` — around 18 — and drag the whole fit with it.\n\nThis is why section 5 filters `TIME > 0`. Real datasets are full of this: a\npre-dose sample that is not really zero, a \"0.00\" that means missing, an assay\nresult below quantification recorded as half the LLOQ. `S0-03` is about\ncatching them before they reach the model.\n\n## What to try next\n\n1. Refit the rich profile with `Q` and `Vp` fixed at the truth. How much better\n   are `CL` and `Vc`? That is the value of borrowing strength, measured.\n2. Simulate a missed dose on day 10 (drop one term from the superposition sum)\n   and see how long the trough takes to recover.\n3. Set `ka = 0.15` and refit. Can you tell from the fit alone that you are in\n   flip-flop?\n\n",
    "supporting": [
      "notebook-py_files"
    ],
    "filters": [],
    "includes": {}
  }
}